name: Community Contribution Label

on:
    workflow_call:
      secrets:
        LE_BOT_APP_ID:
            description: "GitHub App ID for authentication"
            required: true
        LE_BOT_PRIVATE_KEY:
            description: "GitHub App Private Key for authentication"
            required: true
jobs:
  reusable-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            repository: learningequality/.github
            path: .github-repo

      - name: Generate App Token
        id: generate-token
        uses: tibdex/github-app-token@v2
        with:
            app_id: ${{ secrets.LE_BOT_APP_ID }}
            private_key: ${{ secrets.LE_BOT_PRIVATE_KEY }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Add/Remove Community Contribution Label
        run: python .github-repo/scripts/community-contribution-label.py
        env:
          token: ${{ steps.generate-token.outputs.token }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}