name: Manage issue header

on:
    workflow_call:

jobs:
  manage-issue-header:
    runs-on: ubuntu-latest
    if: |
      (github.event.action == 'labeled' && github.event.label.name == 'help wanted') ||
      (github.event.action == 'unlabeled' && github.event.label.name == 'help wanted')
    steps:
      - name: Checkout called repository
        uses: actions/checkout@v3
        with:
          repository: MisRob/.github
          ref: manage-issue-header
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install 
      
      - name: Run script
        id: run-script
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./scripts/manage-issue-header.js');
            return await script({github, context, core});
